refactor: update variable configuration for consistency
go-vela/vela-artifactory pull request #56
Opened 2020-11-19 15:10 UTC by jbrockopp

The first part of this PR is modifying the environment variables and file path arguments we support for the plugin.

The idea is to introduce one consistent standard that all plugins should be able to support 👍 

For environment variables, this pattern will be:

* `PARAMETER_<parameter_name>`
* `<plugin_name>_<parameter_name>`

Using the `action` parameter for this plugin as an example:

* `PARAMETER_ACTION`
* `ARTIFACTORY_ACTION`

For file path arguments, this pattern will be:

* `/vela/parameters/<plugin_name>/<parameter_name>`
* `/vela/secrets/<plugin_name>/<parameter_name>`

Using the `action` parameter again for this plugin as an example:

* `/vela/parameters/artifactory/action`
* `/vela/secrets/artifactory/action`

The second part of this PR is modifying the `DOCS.md` file in the root of the repository to more accurately reflect what we have provided on our external doc site:

https://go-vela.github.io/docs/plugins/pipeline/registry/artifactory/

You'll also notice that I added the supported environment variables to those docs for all the `parameters` we support 👍

2020-12-02 17:14 UTC, KellyMerrick requested changes

2020-12-02 17:14 UTC, KellyMerrick commented on cmd/vela-artifactory/main.go
> +			Usage:    "target registry to promote an image to (uses 'docker_registry' by if empty)",
remove 'by'

2020-12-02 17:18 UTC, jbrockopp commented on cmd/vela-artifactory/main.go
> +			Usage:    "target registry to promote an image to (uses 'docker_registry' by if empty)",
@KellyMerrick fixed 🎉

2020-12-02 22:27 UTC, matt-fevold submitted a review, later dismissed
I like the changes.

I noticed at the bottom there was section for `unchanged files with check annotations` and saw some linter errors that were ignorable, but they made me look at the file `docker_promote.go`. 

Some of the comments seem to be the old versions of your changes which you should consider updating to stay consistent.
i.e. `docker_promote. target_docker_registry ` 
had it's usage updated from `target docker registry is an optional target registry, if null, will use the same name as 'docker_registry` to `tag name of image to promote (promotes all tags if empty)` 
but in the `DockerPromote` struct the comment is the old version.

That said, I don't think it's a big deal either way.  Just pointing it out (you'd probably get rid of the check failure with the new phrasing however in that struct)

2020-12-02 22:27 UTC, matt-fevold commented on cmd/vela-artifactory/main.go
> +			Usage:    "tag name of image to promote (promotes all tags if empty)",
much better phrasing 👍

2020-12-02 22:27 UTC, matt-fevold commented on cmd/vela-artifactory/main.go
> +			Recursive: c.Bool("recursive"),
I like bundling the copy/delete recursive flag together.

2020-12-03 14:20 UTC, jbrockopp commented
@matt-fevold I believe your feedback has been addressed 🎉

2020-12-03 15:20 UTC, matt-fevold approved these changes
LGTM

2020-12-03 18:43 UTC, davidvader approved these changes

2020-12-03 18:43 UTC, davidvader commented
merge waiting on github actions

2020-12-04 16:03 UTC, merged